### ISSUE TITLE
miui13，运行不起来，点击开始京东任务直接崩溃了

### ISSUE THREAD

**Issue by Fujjj** [MonsterNone/tmall-miao#148]
复现步骤：

1.点击开始京东任务
2.弹出音量0的弹窗，点击确定
3.开始录制或投射内容，点击立即开始
4.闪退

**Comment by goujiazhuangzz** [comment]
我也是！怀疑是安卓12适配问题！好多APP都闪退。据说MIUI13和安卓12 都要求APP支持64位才可以

**Comment by MonsterNone** [comment]
应该是安卓12的问题

**Comment by MonsterNone** [comment]
我稍后试着弄个安卓12试一下

**Comment by dee-lii** [comment]
我的也是同样的问题  小米11U  安卓12miui13  用的autox.js   以下是崩溃的调试信息 `Version: 494
Android: 31
android.os.RemoteException: Remote stack trace:
 at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:553)
 at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:137)
 at android.os.Binder.execTransactInternal(Binder.java:1182)
 at android.os.Binder.execTransact(Binder.java:1146)

java.lang.RuntimeException:Failure delivering result ResultInfo{who=null, request=17777, result=-1, data=Intent { (has extras) }} to activity {org.autojs.autojs/org.autojs.autojs.ui.main.MainActivity_}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Set.add(java.lang.Object)' on a null object reference
android.app.ActivityThread.deliverResults(ActivityThread.java:5446)
......
Caused by:
android.os.RemoteException:Remote stack trace:
 at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:553)
 at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:137)
 at android.os.Binder.execTransactInternal(Binder.java:1182)
 at android.os.Binder.execTransact(Binder.java:1146)`

**Comment by tangmuyang** [comment]
用不了，同12闪退

**Comment by relaxjfy** [comment]
昨天晚上升级了MIUI13，今天运行就闪退了，早知道不升级了

**Comment by Esick0429** [comment]
好像不是miui13的原因，可能是小米手机管家的原因，我升级了手机管家后也会自动闪退，我是MIUI12，卸载手机管家更新后就可以正常运行任务了

**Comment by Esick0429** [comment]
好像不是miui13的原因，可能是小米手机管家的原因，我升级了手机管家后也会自动闪退，我是MIUI12，卸载手机管家更新后就可以正常运行任务了

**Comment by MonsterNone** [comment]
经过测试，原生安卓12没问题。。miui13的安卓12会闪退，报错为一处空指针错误

**Comment by tangmuyang** [comment]
会修复吗，大佬

**Comment by MonsterNone** [comment]
> 会修复吗，大佬

正在试图修复

**Comment by MonsterNone** [comment]
修好了朋友们，感觉像是MIUI13的`Feature`。。。。。。。

V9发布
